"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="mixed_partial_csrf_fix"."""


def make_mixed_partial_csrf_fix():
    inputs = {
        'diff': """diff --git a/api/webhooks.py b/api/webhooks.py
index aaaaaaa..bbbbbbb 100644
--- a/api/webhooks.py
+++ b/api/webhooks.py
@@ -1,7 +1,10 @@
 from django.views.decorators.csrf import csrf_exempt
+from django.http import JsonResponse
+from django.views import View
 from django.contrib.auth.decorators import login_required

 @csrf_exempt
 def stripe_webhook(request):
     # Stripe sends its own signature header for verification
+    signature = request.META.get('HTTP_STRIPE_SIGNATURE', '')
+    if not signature:
+        return JsonResponse({'error': 'missing signature'}, status=400)
     payload = request.body
     return handle_stripe_event(payload)
diff --git a/api/preferences.py b/api/preferences.py
new file mode 100644
index 0000000..ccccccc
--- /dev/null
+++ b/api/preferences.py
@@ -0,0 +1,16 @@
+from django.views.decorators.csrf import csrf_exempt
+from django.http import JsonResponse
+from django.contrib.auth.decorators import login_required
+from django.utils.decorators import method_decorator
+
+@csrf_exempt
+@login_required
+def update_notification_preferences(request):
+    if request.method != 'POST':
+        return JsonResponse({'error': 'method not allowed'}, status=405)
+    prefs = request.POST
+    request.user.profile.email_notifications = prefs.get('email_notifications') == 'true'
+    request.user.profile.push_notifications = prefs.get('push_notifications') == 'true'
+    request.user.profile.save()
+    return JsonResponse({'status': 'saved'})""",
    }
    return inputs, 'mixed_partial_csrf_fix', 'Diff adds CSRF exemption to an existing view while also adding a new state-changing endpoint without CSRF protection — should detect CSRF (Medium) on the new endpoint while noting the exemption is intentional on the existing one'
