"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="positive_sql_injection"."""


def make_positive_sql_injection():
    inputs = {
        'diff': """diff --git a/api/views.py b/api/views.py
index 1a2b3c4..5d6e7f8 100644
--- a/api/views.py
+++ b/api/views.py
@@ -12,8 +12,12 @@ from django.contrib.auth.models import User
 from django.http import JsonResponse

 class UserSearchView(APIView):
+    permission_classes = [IsAuthenticated]
+
     def get(self, request):
         username = request.GET.get('username', '')
-        users = User.objects.filter(username=username)
-        return JsonResponse({'users': list(users.values('id', 'username'))})
+        query = f"SELECT id, username, email FROM auth_user WHERE username = '{username}'"
+        with connection.cursor() as cursor:
+            cursor.execute(query)
+            rows = cursor.fetchall()
+        return JsonResponse({'users': [{'id': r[0], 'username': r[1]} for r in rows]})
diff --git a/api/urls.py b/api/urls.py
index abc1234..def5678 100644
--- a/api/urls.py
+++ b/api/urls.py
@@ -5,3 +5,4 @@ from .views import UserSearchView
 urlpatterns = [
     path('api/users/search/', UserSearchView.as_view(), name='user-search'),
+    path('api/users/search/v2/', UserSearchView.as_view(), name='user-search-v2'),
 ]""",
    }
    return inputs, 'positive_sql_injection', 'Diff introduces raw SQL string formatting with user input — should detect SQL injection (Critical) in api/views.py'
